#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Cisco-Version
version:      0.02
version_from: lib/Cisco/Version.pm
installdirs:  site
requires:
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
